apiVersion: v1
kind: Service
metadata:
  name: in-nginx-07
spec:
  type: NodePort
  ports:
  - port: 8007
    targetPort: 80
  selector:
    app: nginx-07
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx-07
  labels:
    app: nginx-07
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-07
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: nginx-07