apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-9
spec:
  rules:
  - host: in9.lab.ae
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: srv-9-1
            port: 
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: srv-9-2
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: srv-9-1
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-9-1
---
apiVersion: v1
kind: Service
metadata:
  name: srv-9-2
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-9-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-9-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-9-1
  template:
    metadata:
      labels:
        app: app-9-1 
    spec:
      containers:
      - name: nginx 
        image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-9-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-9-2
  template:
    metadata:
      labels:
        app: app-9-2
    spec:
      containers:
      - name: nginx
        image: nginx