# Create Deployment
#deployment#6
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-06
  labels:
    app: app-06
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-06
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
#      name: pod-06
# Tested, pod names came from Deployment name above
      labels:
        app: app-06
---
apiVersion: v1
kind: Service
metadata:
  name: srv-06
spec:
  type: NodePort
  clusterIP: 10.96.1.6
  externalIPs:
  - 192.3.0.6
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 80
    nodePort: 30006
  selector:
    app: app-06