apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/disks/pv-10
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pd-10
  labels:
    app: app-10
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /data
      name: pv-10
  volumes:
  - name: pv-10
    persistentVolumeClaim:
      claimName: pvc-10