# Network LB service using MetaLB --- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-07
  labels:
    app: app-07
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-07
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: app-07
---
apiVersion: v1
kind: Service
metadata:
  name: srv-07
spec:
  type: LoadBalancer
  clusterIP: 10.96.1.7
# external ip tested and works fine
#  externalIPs:
#  - 192.3.0.6
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: app-07