apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-cafe-9
spec:
  rules:
  - host: cafe.com
    http:
      paths:
      - path: /tea
        backend:
          service:
            name: srv-cafe_tea-9
            port: 
              number: 8009
      - path: /coffee
        backend:
          service:
            name: srv-cafe_coffe-9
            port: 
              number: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: srv-cafe_tea-9
  labels:
spec:
  ports:
  - port: 8009
    targetPort: 8080
    protocol: TCP
  selector:
    app: cafe_tea-9
---
apiVersion: v1
kind: Service
metadata:
  name: srv-cafe_coffe-9
spec:
  ports:
  - port: 8009
    targetPort: 8080
    protocol: TCP
  selector:
    app: cafe_coffe-9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cafe_tea-9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cafe_tea-9 
  template:
    metadata:
      labels:
        app: cafe_tea-9 
    spec:
      containers:
      - name: tea 
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cafe_coffe-9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe_coffe-9
  template:
    metadata:
      labels:
        app: cafe_coffe-9
    spec:
      containers:
      - name: coffee
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080