# Create Replica Set
#rs#4
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx-04
  labels:
    app: my_web_rs-04
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my_web_rs-04
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: my_web_rs-04