# Create Replica Set
#rs#5
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx-05
  labels:
    app: my_web_rs-05
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my_web_rs-05
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: my_web_rs-05
---
# Create Pod + NodePort Service -- use App Label to bind the pod and service
#service#5
apiVersion: v1
kind: Service
metadata:
  name: srv-nginx-5
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 80
    nodePort: 30005
  selector:
    app: my_web_rs-05