apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-101 
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce