# Using K8S Ingress-NGINX HTTP/HTTPs load-balancer
# TEST 8
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-11
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: in11.lab.ae
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: srv-11-1
            port: 
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: srv-11-2
            port: 
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: map-11-1
data:
  index.html: |
    <!DOCTYPE html><html><body><h1>CKA-11-1</h1></body></html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: map-11-2
data:
  index.html: |
    <!DOCTYPE html><html><body><h1>CKA-11-2</h1></body></html>
---
apiVersion: v1
kind: Service
metadata:
  name: srv-11-1
  labels:
spec:
#  type: LoadBalancer
  clusterIP: 10.96.1.111
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-11-1
---
apiVersion: v1
kind: Service
metadata:
  name: srv-11-2
spec:
#  type: LoadBalancer
  clusterIP: 10.96.1.112
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-11-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-11-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-11-1
  template:
    metadata:
      labels:
        app: app-11-1 
    spec:
      containers:
      - name: nginx 
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: html
        configMap:
          name: map-11-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-11-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-11-2
  template:
    metadata:
      labels:
        app: app-11-2
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: html
        configMap:
          name: map-11-2