# Network LB service using MetaLB --- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-07-1
  labels:
    app: app-07-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-07-1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: app-07-1
---
apiVersion: v1
kind: Service
metadata:
  name: srv-07-1
spec:
  type: LoadBalancer
  clusterIP: 10.96.1.71
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#    nodePort: 30007
  selector:
    app: app-07-1
---
# Network LB service using MetaLB --- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-07-2
  labels:
    app: app-07-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-07-2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: app-07-2
---
apiVersion: v1
kind: Service
metadata:
  name: srv-07-2
spec:
  type: LoadBalancer
  clusterIP: 10.96.1.72
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#    nodePort: 30007
  selector:
    app: app-07-2