apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-nginx-8
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths: 
      - path: / 
        pathType: Prefix
        backend:
          service: 
            name: srv-nginx-8
            port: 
              number: 8008
      - path: /ysaied
        pathType: Prefix
        backend:
          service: 
            name: srv-nginx-8
            port: 
              number: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: srv-nginx-8
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8008
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginx-8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx-8
  labels:
    app: nginx-8
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-8
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
      labels:
        app: nginx-8