apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-stgen-2
  labels:
    app: tgen-2
  namespace: ns2  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgen-2
  template:
    spec:
      containers:
      - name: stgen
        image: ysaied/stgen
    metadata:
      labels:
        app: tgen-2
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tgen-2
  labels:
    app: tgen-2
  namespace: ns2  
spec:
#  type: NodePort
  type: ClusterIP
  clusterIP: 191.3.0.102
  ports:
  - name: iperf
    protocol: TCP
    port: 5001
    targetPort: 5001
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  selector:
    app: tgen-2
---
apiVersion: v1
kind: Pod
metadata:
  name: cuatk-2
  labels:
    app: tgen-2
  namespace: ns2  
spec:
  containers:
  - name: cuatk
    image: ysaied/cuatk
    env:
    - name: MY_SRV
      value: "191.3.0.102"
    - name: IPERF_BW_Mbps
      value: "10"
    - name: IPERF_ON
      value: "True"
    - name: ATCK_ON
      value: "True"
    - name: GFILE_ON
      value: "True"
    - name: DNS_ON
      value: "True"
    - name: DLP_ON
      value: "True"