apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "panslotconfigs.paloaltonetworks.com"
spec:
  group: "paloaltonetworks.com"
#  version: "v1beta1"
  scope: "Namespaced"
  names:
    plural: "panslotconfigs"
    singular: "panslotconfig"
    kind: "PanSlotConfig"
  versions: 
  - name: "v1alpha1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            required: ["slot","slotinfo"]
            properties:
             slot:
               type: "string"
               minimum: 1
             slotinfo:
               type: "string"
               minimum: 1

